name: SonarCloud workflow
on:
  push:
    branches:
      - main  # Replace with your default branch (e.g., master or main)
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Disable shallow clones for better analysis
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '23'  # Use the JDK version you need
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed for PR information
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}    # SonarCloud token
